---
  # (1)ホスト名の設定
  - name: main / set hostname
    hostname:
      name: "{{ inventory_hostname }}"

  # (2)NetworkManagerのリゾルバ設定
  - name: main / set resolver setting
    ini_file:
      dest: /etc/NetworkManager/NetworkManager.conf
      section: main
      option: dns
      value: none

  # (3)ネームサービススイッチの設定
  - name: main / deploy nsswitch.conf
    copy:
      src: nsswitch.conf
      dest: /etc/nsswitch.conf
      owner: root
      group: root
      mode: 0644

  # (4)resolv.confの設定
  - name: main / deploy resolv.conf
    copy:
      src: resolv.conf
      dest: /etc/resolv.conf
      owner: root
      group: root
      mode: 0644

  # (5)hostsファイルの設定
  - name: main / deploy hosts ini_file
    template:
      src: hosts.j2
      dest: /etc/hosts
      owner: root
      group: root
      mode: 0644
