---
  # (1)NetworManagerのインストール
  - name: main / install required network libraries
    yum:
      name: "{{ item }}"
      state: installed
    with_items: "{{ network_packages }}"

  # (2)NetworkManagerの起動
  - name: main / start NetworkManager
    systemd:
      name: NetworkManager
      state: started
      enabled: yes

  # (3)Ethernetの接続プロトコル作成
  - name: main / add ethernet connection
    nmcli:
      type: ethernet
      conn_name: "{{ item.conn_name }}"
      ip4: "{{ item.ip4 }}"
      gw4: "{{ item.gw4 }}"
      state: present
    with_items:
      - "{{ network_ethernet }}"

    # (4)bondingモジュールの有効化
    - name: main / load bonding module
      modprobe:
        name: bonding
        state: present

    # (5)bondingの接続プロファイル作成
    - name: main / add bording connection
      nmcli:
        type: bond
        conn_name: "{{ item.conn_name }}"
        mode: "balance-rr"
        state: present
      with_items:
        - "{{ network_bond }}"
      when: ansible_bond0 is not defined

    # (6)bondingの接続プロファイルの編集
    - name: main / modify bonding connection
      nmcli:
        type: bond
        conn_name: "{{ item.conn_name }}"
        ip4: "{{ item.ip4 }}"
        gw4: "{{ item.gw4 }}"
        state: present
      with_items:
        - "{{ network_bond }}"

    # (7)bonding slaveの接続プロファイル作成
    - name: main / add bonding slave connection
      nmcli:
        type: bond-slave
        conn_name: "{{ item.conn_name }}"
        master: "{{ item.master }}"
        state: present
      with_items:
        - "{{ network_bond_slave }}"
        
